groups:
  - name: WebScaling
    rules:
      - alert: HighRequestRate
        expr: ceil((sum(rate(haproxy_frontend_http_requests_total[30s])) / 10)) > max(haproxy_backend_current_server)
        for: 30s
        labels:
         severity: info
         scale: up
        annotations:
          summary: High request rate
      - alert: LowRequestRate
        expr: ceil((sum(rate(haproxy_frontend_http_requests_total[30s])) / 10)) < max(haproxy_backend_current_server)
        for: 30s
        labels:
         severity: info
         scale: down
        annotations:
          summary: Low request rate
